
export const CLEAR_LOADING_STATE = "CLEAR_LOADING_STATE";

//Signup Admin
export const USER_SIGNUP_LOADING = "USER_SIGNUP_LOADING";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAILURE = "USER_SIGNUP_FAILURE";

//signin Admin
export const USER_SIGNIN_LOADING = "USER_SIGNIN_LOADING";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAILURE = "USER_SIGNIN_FAILURE";

//productDetails
export const PRESERVE_USER_DETAILS = "PRESERVE_USER_DETAILS";

//User List
export const FETCH_USER_LIST_LOADING = "FETCH_USER_LIST_LOADING";
export const FETCH_USER_LIST_SUCCESS = "FETCH_USER_LIST_SUCCESS";
export const FETCH_USER_LIST_FAILURE = "FETCH_USER_LIST_FAILURE";

//User Profile
export const FETCH_USER_PROFILE_LOADING = "FETCH_USER_PROFILE_LOADING";
export const FETCH_USER_PROFILE_SUCCESS = "FETCH_USER_PROFILE_SUCCESS";
export const FETCH_USER_PROFILE_FAILURE = "FETCH_USER_PROFILE_FAILURE";

//Create a User
export const CREATE_NEW_USER_LOADING = "CREATE_NEW_USER_LOADING";
export const CREATE_NEW_USER_SUCCESS = "CREATE_NEW_USER_SUCCESS";
export const CREATE_NEW_USER_FAILURE = "CREATE_NEW_USER_FAILURE";

//Update User
export const UPDATE_USER_LOADING = "UPDATE_USER_LOADING";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";

//Delete User
export const DELETE_USER_LOADING = "DELETE_USER_LOADING";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";

//User REFERALs List
export const FETCH_REFERAL_LIST_LOADING = "FETCH_REFERAL_LIST_LOADING";
export const FETCH_REFERAL_LIST_SUCCESS = "FETCH_REFERAL_LIST_SUCCESS";
export const FETCH_REFERAL_LIST_FAILURE = "FETCH_REFERAL_LIST_FAILURE";


export const PRESERVE_EMPLOYEE_DETAILS = "PRESERVE_EMPLOYEE_DETAILS";


//Employee List
export const FETCH_EMPLOYEE_LIST_LOADING = "FETCH_EMPLOYEE_LIST_LOADING";
export const FETCH_EMPLOYEE_LIST_SUCCESS = "FETCH_EMPLOYEE_LIST_SUCCESS";
export const FETCH_EMPLOYEE_LIST_FAILURE = "FETCH_EMPLOYEE_LIST_FAILURE";

//Create a Employee
export const CREATE_NEW_EMPLOYEE_LOADING = "CREATE_NEW_EMPLOYEE_LOADING";
export const CREATE_NEW_EMPLOYEE_SUCCESS = "CREATE_NEW_EMPLOYEE_SUCCESS";
export const CREATE_NEW_EMPLOYEE_FAILURE = "CREATE_NEW_EMPLOYEE_FAILURE";

//Update Employee
export const UPDATE_EMPLOYEE_LOADING = "UPDATE_EMPLOYEE_LOADING";
export const UPDATE_EMPLOYEE_SUCCESS = "UPDATE_EMPLOYEE_SUCCESS";
export const UPDATE_EMPLOYEE_FAILURE = "UPDATE_EMPLOYEE_FAILURE";

//Delete Employee
export const DELETE_EMPLOYEE_LOADING = "DELETE_EMPLOYEE_LOADING";
export const DELETE_EMPLOYEE_SUCCESS = "DELETE_EMPLOYEE_SUCCESS";
export const DELETE_EMPLOYEE_FAILURE = "DELETE_EMPLOYEE_FAILURE";


// View upload
export const VIEW_UPLOAD_LOADING = "VIEW_UPLOAD_LOADING";
export const VIEW_UPLOAD_SUCCESS = "VIEW_UPLOAD_SUCCESS";
export const VIEW_UPLOAD_FAILURE = "VIEW_UPLOAD_FAILURE";

// Feedback

export const FEEDBACK_LOADING = "FEEDBACK_LOADING";
export const FEEDBACK_SUCCESS = "FEEDBACK_SUCCESS";
export const FEEDBACK_FAILURE = "FEEDBACK_FAILURE";
